source('main.R')
mydownload()
mypowerdata <- myread()
print('Plotting Plot4...')
png(file='plot4.png',width=480,height=480,bg="transparent")
par(mfcol=c(2,2))
with(mypowerdata, {
  plot(DateTime, Global_active_power, type="l", xlab="", ylab = "Global Active Power (kilowatts)")
  plot(DateTime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering",col="black")
  lines(DateTime, Sub_metering_2, type="l",col="red")
  lines(DateTime, Sub_metering_3, type="l",col="blue")
  legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),text.col=c("black","red","blue"))
  plot(DateTime, Voltage, type="l", xlab="datetime", ylab="Voltage")
  plot(DateTime, Global_reactive_power, type="l",xlab="datetime", ylab="Global_active_power")
})
dev.off()